# Generated by Django 3.1.5 on 2021-01-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-time_stamp',)},
        ),
    ]
